/**
 * Rendering a validated proposal into files someone else runs.
 *
 * my-db-mate never creates anything in the warehouse — that boundary is the
 * whole product, not a setting. So the advisor's output leaves as text: BigQuery
 * DDL a data engineer reads, reviews and executes themselves, or a dbt scaffold
 * they drop into an existing project. What happens to the warehouse stays the
 * data team's decision, made with their own credentials.
 *
 * Pure string rendering, no I/O and no database access, so the exact bytes a
 * user downloads are what the tests assert on.
 */

export interface RenderableStatement {
  name: string;
  description: string;
  sql: string;
  valid: boolean;
  columns?: { name: string; type: string }[];
}

export interface RenderableMart {
  name: string;
  purpose: string;
  grain: string;
  sourceTables: string[];
  assumptions: string[];
  summaryTables: RenderableStatement[];
}

export interface RenderableProposal {
  marts: RenderableMart[];
  notes?: string;
}

/** A dbt model name, a BigQuery identifier, and a file name all tolerate the
 *  same narrow character set. Anything else the model invented is rewritten
 *  rather than trusted — an identifier is about to be pasted into DDL. */
export function safeIdentifier(raw: string): string {
  const cleaned = raw.trim().toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  // Must not start with a digit, and must not be empty.
  if (!cleaned) return 'unnamed';
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

/** Wrap prose so it can sit inside a SQL comment without terminating it or
 *  smuggling a second statement onto the line. */
function sqlComment(text: string): string {
  return text.replace(/\r?\n/g, ' ').replace(/\*\//g, '* /').trim();
}

/** Only statements that passed validation are rendered. An invalid one would
 *  turn into DDL that fails when the data team runs it, which is precisely the
 *  handoff this export exists to make trustworthy. */
function validStatements(mart: RenderableMart): RenderableStatement[] {
  return mart.summaryTables.filter((s) => s.valid);
}

/**
 * BigQuery standard-SQL DDL for the whole proposal.
 *
 * Views, not tables: a view costs nothing to create, re-reads live data, and is
 * trivially reversible — the right first step for a design that has not been
 * proven in production yet. The header says plainly that nothing has been run.
 */
export function renderBigQueryDdl(proposal: RenderableProposal, targetDataset: string): string {
  const ds = targetDataset.trim() || 'marts';
  const out: string[] = [
    '-- Datamart proposal generated by my-db-mate.',
    '-- NOTHING HERE HAS BEEN EXECUTED. Review it, then run it yourself with your',
    '-- own credentials — my-db-mate holds read-only access and never writes to a warehouse.',
    `--`,
    `-- Target dataset: ${sqlComment(ds)}`,
    '',
  ];
  if (proposal.notes) out.push(`-- Note: ${sqlComment(proposal.notes)}`, '');

  for (const mart of proposal.marts) {
    const stmts = validStatements(mart);
    if (stmts.length === 0) continue;
    out.push(
      '-- ' + '='.repeat(70),
      `-- Mart: ${sqlComment(mart.name)}`,
      `-- Purpose: ${sqlComment(mart.purpose)}`,
      `-- Grain:   ${sqlComment(mart.grain)}`,
      `-- Sources: ${mart.sourceTables.map(sqlComment).join(', ')}`,
    );
    for (const a of mart.assumptions) out.push(`-- Assumes: ${sqlComment(a)}`);
    out.push('-- ' + '='.repeat(70), '');

    for (const s of stmts) {
      const view = `${safeIdentifier(mart.name)}__${safeIdentifier(s.name)}`;
      out.push(
        `-- ${sqlComment(s.description)}`,
        `CREATE OR REPLACE VIEW \`${ds}.${view}\` AS`,
        s.sql.trim().replace(/;\s*$/, ''),
        ';',
        '',
      );
    }
  }
  return out.join('\n');
}

export interface DbtFile {
  path: string;
  contents: string;
}

/**
 * A dbt scaffold: one `.sql` model per validated statement, plus the `schema.yml`
 * documenting them.
 *
 * The column list in `schema.yml` comes from what the warehouse said the query
 * returns, not from parsing the SQL — so the documentation matches the model
 * even where the SQL is doing something the renderer does not understand.
 */
export function renderDbtScaffold(proposal: RenderableProposal): DbtFile[] {
  const files: DbtFile[] = [];
  const models: string[] = [];

  for (const mart of proposal.marts) {
    const martDir = safeIdentifier(mart.name);
    for (const s of validStatements(mart)) {
      const model = `${martDir}__${safeIdentifier(s.name)}`;
      files.push({
        path: `models/${martDir}/${model}.sql`,
        contents:
          `-- ${sqlComment(s.description)}\n` +
          `-- Grain: ${sqlComment(mart.grain)}\n` +
          `{{ config(materialized='view') }}\n\n` +
          `${s.sql.trim().replace(/;\s*$/, '')}\n`,
      });
      models.push(
        `  - name: ${model}\n` +
        `    description: "${yamlString(s.description)}"\n` +
        (s.columns?.length
          ? `    columns:\n` +
            s.columns
              .map((c) => `      - name: ${safeIdentifier(c.name)}\n        description: "${yamlString(c.type)}"\n`)
              .join('')
          : ''),
      );
    }
  }

  const header =
    `version: 2\n\n` +
    `# Generated by my-db-mate from a datamart proposal.\n` +
    `# Nothing was created in the warehouse — this is a scaffold for your own dbt project.\n` +
    (proposal.notes ? `# Note: ${sqlComment(proposal.notes)}\n` : '') +
    `\nmodels:\n`;

  files.push({ path: 'models/schema.yml', contents: models.length ? header + models.join('') : header });
  return files;
}

/** Escape for a double-quoted YAML scalar, and flatten newlines so a multi-line
 *  description cannot break out of the value. */
function yamlString(raw: string): string {
  return raw.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, ' ').trim();
}
